model:
  base_learning_rate: 5.0e-5
  target: ldm.models.autoencoder.AutoencoderKLResi
  params:
    # for training only
    ckpt_path:  D:/cqy/stableSR/logs/2024-10-15T14-52-23_Tik_CFW_256-512/checkpoints/last.ckpt
    monitor: "val/rec_loss"
    embed_dim: 4
    fusion_w: 0.5
    freeze_dec: True
    synthesis_data: False
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 501
        kl_weight: 0
        disc_weight: 0.025
        disc_factor: 1.0

    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 512
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    image_key: 'gt'


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 6
    wrap: True
    train:
      target: basicsr.data.single_image_dataset.SingleImageNPDataset
      params:
        gt_path: ['D:/cqy/stableSR/CFW_evaldata/phase_ADMM/']
        io_backend:
          type: disk
    validation:
      target: basicsr.data.single_image_dataset.SingleImageNPDataset
      params:
        gt_path: ['D:/cqy/stableSR/CFW_evaldata/phase_ADMM/']
        io_backend:
          type: disk
    test:
      target: basicsr.data.single_image_dataset.SingleImageNPDataset
      params:
        gt_path: [ 'D:/cqy/stableSR/CFW_evaldata/phase_ADMM' ]
        io_backend:
          type: disk

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 1500
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 4
        increase_log_steps: False
        log_on_batch_idx: True


  trainer:
    benchmark: True
    max_steps: 800000
    accumulate_grad_batches: 8
    check_val_every_n_epoch: 10
    #    limit_train_batches: 0.2
    #    limit_test_batches: 1
    #    limit_val_batches: 0.1
